site_name: Autoware Documentation
site_url: https://tier4.github.io/autoware.proj
repo_url: https://github.com/tier4/autoware.proj
edit_uri: edit/main/
docs_dir: .
theme:
  name: material
  feature:
    tabs: true
  favicon: docs/images/tier4.png
  icon:
    repo: fontawesome/brands/github
extra:
  font:
    text: "Noto Sans JP"
    code: "Consolas"
plugins:
  - same-dir
  - search
  - exclude:
      glob:
        - "src/*"
        - "build/*"
        - "install/*"
        - "log/*"
copyright: "Copyright &copy; 2021 Tier IV, Inc."

markdown_extensions:
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - mdx_math
  - mdx_truly_sane_lists: { nested_indent: 2 }
  - mdx_unimoji
  - plantuml_markdown: { server: "http://www.plantuml.com/plantuml" }
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - toc: { permalink: "#" }

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - docs/css/tier4_color.css
extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

nav:
  - Home: docs/Readme.md
  - Tutorials:
      - Requirements: docs/tutorial/Requirements.md
      - How to install: docs/tutorial/HowToInstall.md
      - How to run:
          - Quick start: docs/tutorial/QuickStart.md
          - Simulation: docs/tutorial/SimulationTutorial.md
  - Design:
      - Architecture:
          - Overview: docs/design/software_architecture/Overview.md
          - Sensing: docs/design/software_architecture/Sensing/Sensing.md
          - Localization:
              - Overall: docs/design/software_architecture/Localization/Localization.md
              - Pose estimator: docs/design/software_architecture/Localization/PoseEstimator/PoseEstimator.md
              - Twist estimator: docs/design/software_architecture/Localization/TwistEstimator/TwistEstimator.md
              - Pose twist fusion filter: docs/design/software_architecture/Localization/PoseTwistFusionFilter/PoseTwistFusionFilter.md
          - Perception:
              - Overall: docs/design/software_architecture/Perception/Perception.md
              - Object recognition:
                  - Detection: docs/design/software_architecture/Perception/ObjectRecognition/Detection/Detection.md
                  - Tracking: docs/design/software_architecture/Perception/ObjectRecognition/Tracking/Tracking.md
                  - Prediction: docs/design/software_architecture/Perception/ObjectRecognition/Prediction/Prediction.md
              - Traffic light recognition:
                  - Detection: docs/design/software_architecture/Perception/TrafficLightRecognition/Detection/Detection.md
                  - Classification: docs/design/software_architecture/Perception/TrafficLightRecognition/Classification/Classification.md
          - Planning:
              - Overall: docs/design/software_architecture/Planning/Planning.md
              - Scenario selector: docs/design/software_architecture/Planning/ScenarioSelector/ScenarioSelector.md
              - Lane driving Scenario:
                  - Overall: docs/design/software_architecture/Planning/LaneDriving/LaneDrivingScenario.md
                  - Behavior path planning: docs/design/software_architecture/Planning/LaneDriving/Behavior/LaneChangePlanner.md
                  - Behavior velocity planning: docs/design/software_architecture/Planning/LaneDriving/Behavior/BehaviorVelocityPlanner.md
              - Parking: docs/design/software_architecture/Planning/Parking/ParkingScenario.md
              - Design rationale: docs/design/software_architecture/Planning/DesignRationale.md
          - Control:
              - Overall: docs/design/software_architecture/Control/Control.md
              - Trajectory follower:
                  - Lateral controller: docs/design/software_architecture/Control/TrajectoryFollower/LateralController.md
                  - Longitudinal controller: docs/design/software_architecture/Control/TrajectoryFollower/LongitudinalController.md
                  - Lateral longitudinal coupler: docs/design/software_architecture/Control/TrajectoryFollower/LatLonCoupler.md
              - Vehicle cmd gate: docs/design/software_architecture/Control/VehicleCmdGate/VehicleCmdGate.md
          - Vehicle: docs/design/software_architecture/Vehicle/Vehicle.md
          - Map: docs/design/software_architecture/Map/Map.md
          - TF: docs/design/software_architecture/TF.md
          - Naming convention: docs/design/software_architecture/NamingConvention.md
          - For developers: docs/design/software_architecture/ForDevelopers.md
          - Node diagram: docs/design/software_architecture/NodeDiagram.md
      - Repository: docs/design/repository/Repository.md
      - Release: docs/design/release/Release.md
  - DeveloperGuide:
      - Coding guideline: docs/developer_guide/CodingGuideline.md
      - Pull request guideline: docs/developer_guide/PullRequestGuideline.md
      - Unit test Guideline: docs/developer_guide/UnitTestGuideline.md
      - Knowhow:
          - docs/developer_guide/knowhow/PortingToROS2.md
  - License/Credit:
      - Credits: docs/Credits.md
      - License: docs/LICENSE
