name: sync internal

on:
  schedule:
    - cron: "0 20 * * *" # run at 5 AM JST
  workflow_dispatch:

env:
  BASE_BRANCH: main
  SYNC_TARGET_BRANCH: main-internal

jobs:
  sync-internal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Set git config
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com.insteadOf 'https://github.com'
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"

      - name: Merge internal
        run: |
          git merge "origin/${{ env.SYNC_TARGET_BRANCH }}"
          git push origin "${{ env.BASE_BRANCH }}"
